version: '3.4'

services:
  test: &test
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
       PYTHON_VERSION: 3.7.3
    image: "lkml-lint"
    command: scripts/run_tests.sh --format-code
    volumes:
      - ./:/workdir
