include: "/autogenerated_views/order_items.view"
include: "/**/*value_format_names*"

#base reordered{
# dimension: id {}
# dimension: user_id {}
# dimension: order_id {}
# dimension: inventory_item_id {}
# dimension: sale_price {}
# dimension: status {}
# dimension_group: created {}
# dimension_group: shipped {}
# dimension_group: delivered {}
# dimension_group: returned {}
# measure: count {}
#}end__base reordered

view: order_items_custom_fields {
  extends: [order_items]
  dimension: status_raw {type:string hidden:yes sql:${TABLE}.status;;}
  dimension: status {
    case: {
      when: {sql: ${status_raw}='Cancelled' ;; label: "Cancelled"}
      when: {sql: ${status_raw}='Complete' ;; label: "Complete"}
      when: {sql: ${status_raw}='Processing' ;; label: "Processing"}
      when: {sql: ${status_raw}='Returned' ;; label: "Returned"}
      when: {sql: ${status_raw}='Shipped' ;; label: "Shipped"}
      else: "Unknown"
    }
  }
  measure: total_sale_price {
    type: sum
    sql: ${sale_price} ;;
  }
  measure: average_sale_price {
    type: average
    sql: ${sale_price} ;;
  }
  dimension_group: days_created_to_shipped {
    type: duration
    intervals: [second,minute,hour,week,month,quarter,year]
    sql_start: ${created_raw} ;;
    sql_end: ${shipped_raw} ;;
  }
  measure: order_count {
    type: count_distinct
    sql: ${order_id} ;;
  }
}

#base reordered + custom{
# dimension: id                 {}
# dimension: user_id            {}
# dimension: order_id           {}
# dimension: inventory_item_id  {}
# dimension: sale_price         {}
# dimension_group: created      {}
# dimension_group: shipped      {}
# dimension_group: delivered    {}
# dimension_group: returned     {}
# measure: count                {}
# dimension: status             {}
# measure: total_sale_price     {}
# measure: average_sale_price   {}
# dimension_group: days_created_to_shipped {}
# measure: order_count   {}
#}end__base reordered + custom

view: order_items__hide_system_keys {
dimension: id                 {hidden:yes}
dimension: user_id            {hidden:yes}
dimension: order_id           {hidden:yes}
dimension: inventory_item_id  {hidden:yes}
}

view: order_items__testing_override_unhide_all {
dimension: id                 {hidden:no}
dimension: user_id            {hidden:no}
dimension: order_id           {hidden:no}
dimension: inventory_item_id  {hidden:no}
dimension: sale_price         {hidden:no}
dimension_group: created      {hidden:no}
dimension_group: shipped      {hidden:no}
dimension_group: delivered    {hidden:no}
dimension_group: returned     {hidden:no}
measure: count                {hidden:no}
dimension: status             {hidden:no}
measure: total_sale_price     {hidden:no}
measure: average_sale_price   {hidden:no}
dimension_group: days_created_to_shipped {hidden:no}
measure: order_count   {hidden:no}
}

view: order_items__descriptions {
measure: count            {description:"number of items ever ordered"}
dimension: status           {description:"order status (not by order item)"}
}

view: order_items__view_labels {
  dimension: status             {view_label:"Orders"}
  dimension_group: created      {view_label:"Orders"}
  dimension_group: shipped      {view_label:"Orders"}
  dimension_group: delivered    {view_label:"Orders"}
  dimension_group: returned     {view_label:"Orders"}
  dimension_group: days_created_to_shipped {view_label:"Orders"}
  measure: order_count   {view_label:"Orders"}
}



view: order_items__group_labels {
dimension: id                 {group_label:"System Keys"}
dimension: user_id            {group_label:"System Keys"}
dimension: order_id           {group_label:"System Keys"}
dimension: inventory_item_id  {group_label:"System Keys"}
}

view: order_items__labels {
  measure: count {label:"Order Item Count"}
}

view: order_items_base {
  extends: [
    #these likely need to come first so that sql and types are established
    order_items
    ,order_items_custom_fields

    #labeling and formatting
    ,order_items__labels
    ,order_items__group_labels
    ,order_items__descriptions
#     ,order_items__value_formats

    ,order_items__hide_system_keys
#     ,users_anonymized_by_hiding

# #     ,users__testing_override_unhide_all

    #security
# #     ,users_anonymized_using_access_grant
# #     ,users_admin_access_grants_override
    ,order_items__view_labels
  ]
}
