version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/lkml

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Check types
          command: |
            . venv/bin/activate
            mypy lkml

      - run:
          name: Check Black formatting
          command: |
            . venv/bin/activate
            black --check .

      - run:
          name: Check flake8
          command: |
            . venv/bin/activate
            flake8

      - run:
          name: Check bandit security warnings
          command: |
            . venv/bin/activate
            bandit -r .

      - run:
          name: iSort import sorting
          command: |
            . venv/bin/activate
            isort -rc -c lkml scripts

      - run:
          name: Test
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest tests

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

      - codecov/upload:
          file: coverage.xml
